package com.padel.backend.domain;

import static com.padel.backend.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CanchaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanchaAllPropertiesEquals(Cancha expected, Cancha actual) {
        assertCanchaAutoGeneratedPropertiesEquals(expected, actual);
        assertCanchaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanchaAllUpdatablePropertiesEquals(Cancha expected, Cancha actual) {
        assertCanchaUpdatableFieldsEquals(expected, actual);
        assertCanchaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanchaAutoGeneratedPropertiesEquals(Cancha expected, Cancha actual) {
        assertThat(actual)
            .as("Verify Cancha auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanchaUpdatableFieldsEquals(Cancha expected, Cancha actual) {
        assertThat(actual)
            .as("Verify Cancha relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a ->
                assertThat(a.getPrecio()).as("check precio").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrecio())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCanchaUpdatableRelationshipsEquals(Cancha expected, Cancha actual) {
        // empty method
    }
}
