package com.padel.backend.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HorarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAllPropertiesEquals(Horario expected, Horario actual) {
        assertHorarioAutoGeneratedPropertiesEquals(expected, actual);
        assertHorarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAllUpdatablePropertiesEquals(Horario expected, Horario actual) {
        assertHorarioUpdatableFieldsEquals(expected, actual);
        assertHorarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioAutoGeneratedPropertiesEquals(Horario expected, Horario actual) {
        assertThat(actual)
            .as("Verify Horario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioUpdatableFieldsEquals(Horario expected, Horario actual) {
        assertThat(actual)
            .as("Verify Horario relevant properties")
            .satisfies(a -> assertThat(a.getDia()).as("check dia").isEqualTo(expected.getDia()))
            .satisfies(a -> assertThat(a.getHoraInicio()).as("check horaInicio").isEqualTo(expected.getHoraInicio()))
            .satisfies(a -> assertThat(a.getHoraFin()).as("check horaFin").isEqualTo(expected.getHoraFin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHorarioUpdatableRelationshipsEquals(Horario expected, Horario actual) {
        assertThat(actual)
            .as("Verify Horario relationships")
            .satisfies(a -> assertThat(a.getCancha()).as("check cancha").isEqualTo(expected.getCancha()));
    }
}
